### ISSUE TITLE
Install errors

### ISSUE THREAD

**Issue by mdcarlson** [tcnksm/cf-plugin-update-cli#1]
When I follow the installation instructions, I get the following errors:

```
./plugin.go:192: unknown plugin.PluginMetadata field 'Version' in struct literal
./plugin.go:199: unknown plugin.Command field 'UsageDetails' in struct literal
./version.go:15: undefined: plugin.VersionType    
```

Full install log here:  https://gist.github.com/mdcarlson/9bb5160693741a27032f

I am using golang 1.6 on Mac OS X Yosemite.

```
go version go1.6 darwin/amd64
```

Any suggestions?

**Comment by tcnksm** [comment]
Hi, 

I think your local `github.com/cloudfoundry/cli` is old. Can you try to update it ? 

I'll update `Makefile` to use latest package.

**Comment by tcnksm** [comment]
I prepared my own plugin repository (only for experimental). Please try the following,

``` bash
$ cf add-plugin-repo tcnksm https://t-plugins.au-syd.mybluemix.net
$ cf install-plugin -r tcnksm update-cli
```

**Comment by tcnksm** [comment]
Please open issue again if you can not install.

**Comment by mdcarlson** [comment]
Sorry for the delay.  When I deleted the `$GOPATH/src/github.com/cloudfoundry/cli` subfolder and re-ran `make install`, the process completed successfully.

I then uninstalled the plugin using `make  uninstall` and followed the directions to install from your experimental plugin repo.  That also succeeded with no errors.

Thanks!

**Comment by tcnksm** [comment]
Great ! Thank you for reporting that :+1:
