### ISSUE TITLE
update-cli does not accept Y for upgrade on Windows

### ISSUE THREAD

**Issue by ibakirov** [tcnksm/cf-plugin-update-cli#3]
Environment: Windows 10 Pro x64 Eng

Can't update cf cli to latest version on Windows 10 Pro, update cli does not accept Y (or y) for update

![cf-update-cli](https://user-images.githubusercontent.com/7983476/28773469-83f3e466-760b-11e7-8792-a295852b7c37.png)

**Comment by CAFxX** [comment]
@ibakirov would you be able to send us a PR for this?

**Comment by ibakirov** [comment]
Unfortunately I abandoned using this plugin and upgrading CF CLI from release binaries.
